name: contentstack
description: Contentstack is a headless CMS with an API-first approach that puts content at the centre.
version: 1.0.0
homepage: www.contentstack.com
documentation: https://www.contentstack.com/docs/developers/apis/content-delivery-api
api_documentation: https://www.contentstack.com/docs/developers/dart/api-reference

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  dartdoc: ^6.2.2 # dartdoc to generate HTML documentation for your Dart package
  http: ^0.13.3 # Future-based API for HTTP requests
  json_annotation: ^4.4.0 # create code for JSON serialization and deserialization.
  logger: ^2.3.0 # logger which prints beautiful logs
  path: ^1.8.0 # for manipulating paths: joining, splitting, normalizing, etc.
#  super_enum: ^0.5.0
  freezed: ^2.0.0
  freezed_annotation: ^2.0.0
  dotenv: ^4.2.0 # loads environment variables at runtime from a .env file.

dev_dependencies:
  flutter_lints: ^2.0.3
  build_runner: ^2.0.4
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
  json_serializable: ^6.1.5
  test: ^1.20.1
